### PR TITLE
auth setup done

### PR DESCRIPTION
**Pull request by Chiranjeev-droid**

### CODE REVIEW

**Review by KapadiaNaitik — APPROVED** [review]
Apart from next-auth not working on other URL's and port everything is fine.Mostly will be fixed in production.

**Comment by Palanikannan1437** [comment]
@KapadiaNaitik even after being signed in, this happens when I go to the "schedule" page! Please check this out!

why

**Comment by Palanikannan1437** [comment]
@KapadiaNaitik could you please clarify the entire flow of how the "landing" page and schedule page works?

I'm able to just see 2 events in the in the landing page!

**Comment by Chiranjeev-droid** [comment]
> @KapadiaNaitik could you please clarify the entire flow of how the "landing" page and schedule page works?
> 
> I'm able to just see 2 events in the in the landing page!

because  from backend only 2  fake events are coming. and right now in this commit the session is going to schedule page also but the schedule page has not been taken care.

**Pull request merged**
